apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: grafana-
commonLabels:
  app: grafana
resources:
  - ../../hacks/kustomize/transformer-configs
  - helm.yaml
secretGenerator:
  - name: values
    files:
      - values.yaml
