apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: staging
namespace: staging
commonAnnotations:
  fluxcd.io/tag.app: "glob:staging-*"
resources:
  - namespace.yaml
  - ../../../../business-apps/app1
  - ../../../../business-apps/app2
