apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: staging
namespace: staging
resources:
  - namespace.yaml
  - ../../../../business-apps/app1
  - ../../../../business-apps/app2
