apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.2.0
  valuesFrom:
    - secretKeyRef:
        name: flux-values
