apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: flux
resources:
  - ../../hacks/kustomize/transformer-configs
  - helm.yaml
secretGenerator:
  - name: flux-values
    files:
      - values.yaml
