sync:
  state: secret
git:
  url: "git@github.com:slamdev/multicluster-gitops"
  user: "gitops"
  email: "gitops@gitops.com"
  setAuthor: false
  ciSkip: false
  pollInterval: "60s"
  secretName: "flux-github-identity"
registry:
  automationInterval: "60s"
  includeImage: "docker.io/slamdev/*"
# remove as soon as issue is fixed
# https://github.com/fluxcd/flux/issues/2936
additionalArgs:
  - "--registry-include-image=docker.io/slamdev/*"
syncGarbageCollection:
  enabled: true
manifestGeneration: true
