sync:
  state: secret
git:
  url: "git@github.com:slamdev/multicluster-gitops"
  user: "gitops"
  email: "gitops@gitops.com"
  setAuthor: false
  ciSkip: false
  pollInterval: "60s"
  secretName: "flux-github-identity"
registry:
  automationInterval: "60s"
  # TODO: option is available in master only, so it will make no effect with current version
  includeImage: "docker.io/slamdev/*"
syncGarbageCollection:
  enabled: true
manifestGeneration: true
