---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-app
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/backend:dev-21a976
        name: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-app
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/frontend:dev-1b38e9
        name: app
