---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-app
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/nginx:6f793b
        name: app
