apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: team-b
namespace: team-b
commonAnnotations:
  fluxcd.io/tag: "glob:team-b-*"
resources:
  - namespace.yaml
  - ../../../../business-apps/app1
