apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  env: prod
commonAnnotations:
  flux.weave.works/tag.app: glob:prod-*
replicas:
  - name: app
    count: 2
resources:
  - ../../../bases/frontend
