apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: docker.io/slamdev/http-echo
          ports:
            - name: http
              containerPort: 8080
