apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  env: prod
replicas:
  - name: app
    count: 3
resources:
  - ../../../bases/backend
patchesStrategicMerge:
  - deployment-patch.yaml
