apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          image: docker.io/slamdev/app1:493640
          ports:
            - name: http
              containerPort: 8080
