---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/app1:prod-4a19fe
        name: app
