---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/app1:staging-4e71c9
        name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/app2:staging-c367f3
        name: app
