apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io
    name: helm-operator
    version: 1.2.0
  valuesFrom:
    - secretKeyRef:
        name: helm-operator-values
