apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: helm-operator
resources:
  - ../../hacks/kustomize/transformer-configs
  - helm.yaml
secretGenerator:
  - name: helm-operator-values
    files:
      - values.yaml
