---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-app
  namespace: prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/backend:prod-92b1ef
        name: app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-app
  namespace: prod
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: app
      containers:
      - image: docker.io/slamdev/frontend:prod-64af49
        name: app
