apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: monitoring
namespace: monitoring
resources:
  - namespace.yaml
  - ../../../../ops-apps/grafana
  - ../../../../ops-apps/promtail
